### ISSUE TITLE
Gradle tests fail for me

### ISSUE THREAD

**Issue by dicer** [k3b/CalendarIcsAdapter#17]
When running "gradle build" on the release-fdroid branch I get failed tests. Might be my timezone (Hong Kong), but not sure. Any ideas?
:libIcsJ2se:test

de.k3b.calendar.DtoIcRegressonsTests > shouldBeSameMaximal FAILED
    org.junit.ComparisonFailure at DtoIcRegressonsTests.java:312

de.k3b.calendar.DtoIcRegressonsTests > shouldBeSameFixThisAndAllFurtherEvents FAILED
    org.junit.ComparisonFailure at DtoIcRegressonsTests.java:326

de.k3b.calendar.DtoIcRegressonsTests > shouldBeSameFixAllEvents FAILED
    org.junit.ComparisonFailure at DtoIcRegressonsTests.java:333

31 tests completed, 3 failed
:libIcsJ2se:test FAILED

The test says things like:
Failed tests
shouldBeSameFixAllEvents
org.junit.ComparisonFailure: expected:<...1SU
RDATE:19610901T0[45612,19630901T045612
EXDATE:19710901T045612,19730901T04]5612
END:VEVENT
END:...> but was:<...1SU
RDATE:19610901T0[35612,19630901T035612
EXDATE:19710901T035612,19730901T03]5612
END:VEVENT
END:...>

Sorry, can't seem to upload the test result here cause it's html.

**Comment by k3b** [comment]
In the tests the date-time was set relative to local time zone and then translated to utc/gmt. i changed the testcode by explictly setting the local timezone to cet. that should fix the problem.

Note: i have set the regression tests to Ignore because travis-ci build-server produces a slightly different output for some tests.
